apiVersion: batch/v1
kind: CronJob
metadata:
  name: opentow-tick
spec:
  schedule: "* * * * *" # Runs every minute
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: opentow-tick
              image: us-central1-docker.pkg.dev/opentow-498815/opentow-repo/opentow:latest
              imagePullPolicy: IfNotPresent
              command: ["python", "opentow.py", "tick"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: opentow-db-secret
                      key: DATABASE_URL
              volumeMounts:
                - name: config-volume
                  mountPath: /app/config.default.xml
                  subPath: config.default.xml
          volumes:
            - name: config-volume
              configMap:
                name: opentow-config