apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentow-db
  template:
    metadata:
      labels:
        app: opentow-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "opentow"
            - name: POSTGRES_PASSWORD
              value: "opentowpass"
            - name: POSTGRES_DB
              value: "opentowdb"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: opentow-db
spec:
  selector:
    app: opentow-db
  ports:
    - port: 5432
      targetPort: 5432